---
application:
  name: "evelyn"
  project: "MissEvelyn"
  organization: "QoveryCommunity"
databases:
- type: "MONGODB"
  name: "evie"
  version: "4.4"
routers:
- name: "main-evelyn"
  routes:
  - application_name: "evelyn"
    paths:
    - "/*"
